import { z } from 'zod';
import { FamilyReadSchema } from './family.js';
import { ParentReadSchema } from './parent.js';
import { ChildReadSchema } from './child.js';
import { ChildVisitReadSchema } from './child-visit.js';
import { FamilyVisitReadSchema } from './family-visit.js';
import { CommunityReadSchema, SiteReadSchema, ResourceReadSchema, TrainingReadSchema, ChildVisitQuestionReadSchema, ParentVisitQuestionReadSchema, FamilyVisitQuestionReadSchema } from './lookups.js';

// Entity types for sync operations
export const SyncEntitySchema = z.enum([
  'family',
  'parent',
  'child',
  'childVisit',
  'familyVisit',
  'birthingAssistant'
]);

// Entity types that can appear as a tombstone in serverChanges.deleted.
// Superset of SyncEntitySchema: clients cache the lookup tables too, and those
// rows are soft-deleted by admins, so a client must be told to drop them.
export const SyncDeletableEntitySchema = z.enum([
  'family',
  'parent',
  'child',
  'childVisit',
  'familyVisit',
  'birthingAssistant',
  'community',
  'site',
  'resource',
  'training',
  'childVisitQuestion',
  'parentVisitQuestion',
  'familyVisitQuestion',
]);

/**
 * A record that was soft-deleted on the server.
 *
 * Soft-deleted rows are filtered out of every other array in ServerChanges, so
 * without a tombstone an offline client would keep a deleted record forever —
 * it simply stops appearing in the delta. `localId` is present when the record
 * originated on a client, letting it be matched before the server id is known.
 */
export const SyncTombstoneSchema = z.object({
  entity: SyncDeletableEntitySchema,
  id: z.number().int().positive(),
  localId: z.string().uuid().nullable().default(null),
  deletedAt: z.string().datetime(),
});

// Sync operation types (only "create" is allowed from clients)
export const SyncOperationSchema = z.enum(['create']);

// Individual sync change item
export const SyncChangeSchema = z.object({
  entity: SyncEntitySchema,
  operation: SyncOperationSchema,
  localId: z.string().uuid(), // UUID generated by client for this offline record
  parentLocalId: z.string().uuid().optional(), // For referencing parent records in same batch
  data: z.record(z.any()), // The actual entity data (will be validated against specific schemas)
  changedAt: z.string().datetime(), // When this change was made offline
});

// Sync request schema
export const SyncRequestSchema = z.object({
  lastSyncedAt: z.string().datetime().nullable(), // null for first sync
  changes: z.array(SyncChangeSchema).max(100), // Limit batch size
});

// Individual sync result
export const SyncResultSchema = z.object({
  localId: z.string().uuid(),
  serverId: z.number().int().positive().optional(), // Only present for successful creates
  status: z.enum(['created', 'already_exists', 'error']),
  error: z.string().optional(), // Error message if status is 'error'
});

// Server changes for pulling data
export const ServerChangesSchema = z.object({
  families: z.array(FamilyReadSchema),
  parents: z.array(ParentReadSchema),
  children: z.array(ChildReadSchema),
  childVisits: z.array(ChildVisitReadSchema),
  familyVisits: z.array(FamilyVisitReadSchema),
  // All lookup tables are included in every sync
  lookups: z.object({
    communities: z.array(CommunityReadSchema),
    sites: z.array(SiteReadSchema),
    resources: z.array(ResourceReadSchema),
    training: z.array(TrainingReadSchema),
    childVisitQuestions: z.array(ChildVisitQuestionReadSchema),
    parentVisitQuestions: z.array(ParentVisitQuestionReadSchema),
    familyVisitQuestions: z.array(FamilyVisitQuestionReadSchema),
  }),
  // Records soft-deleted since lastSyncedAt. Empty on a first sync (lastSyncedAt
  // null), because a client with no local data has nothing to delete.
  deleted: z.array(SyncTombstoneSchema).default([]),
});

// Sync response schema
export const SyncResponseSchema = z.object({
  syncedAt: z.string().datetime(), // Server timestamp for this sync
  results: z.array(SyncResultSchema), // Results for each change in the request
  serverChanges: ServerChangesSchema, // Data to pull from server
  errors: z.array(z.string()).default([]), // Global errors if any
});

// Inferred types for TypeScript
export type SyncEntity = z.infer<typeof SyncEntitySchema>;
export type SyncDeletableEntity = z.infer<typeof SyncDeletableEntitySchema>;
export type SyncTombstone = z.infer<typeof SyncTombstoneSchema>;
export type SyncOperation = z.infer<typeof SyncOperationSchema>;
export type SyncChange = z.infer<typeof SyncChangeSchema>;
export type SyncRequest = z.infer<typeof SyncRequestSchema>;
export type SyncResult = z.infer<typeof SyncResultSchema>;
export type ServerChanges = z.infer<typeof ServerChangesSchema>;
export type SyncResponse = z.infer<typeof SyncResponseSchema>;