name: Build

on:
  pull_request:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: |
            cd packages/backend
            npx prisma generate

      - name: Build monorepo
        run: pnpm build
